spring.application.name=survay


spring.datasource.url=jdbc:mysql://localhost:3306/sabita
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
